name: Production Auto-PR
on:
  push:
    branches: ['dev']
  workflow_dispatch:

jobs:
  pull-request:
    name: Open PR to production
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: pull-request
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: "prod"
        pr_title: "Pulling ${{ github.ref }} into main"
        pr_body: "💥 *An automated PR*"
        pr_draft: false
        github_token: ${{ secrets.GH_TOKEN }}